// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrk1fJinFTE-RHaKOZf3ChbCDq0AISM2s',
    appId: '1:171530435946:web:3cbe1e28365f1016957913',
    messagingSenderId: '171530435946',
    projectId: 'quest-baldy-dash',
    authDomain: 'quest-baldy-dash.firebaseapp.com',
    storageBucket: 'quest-baldy-dash.appspot.com',
    measurementId: 'G-GFTBBSY5GF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD02YSEsR3HLwm8pbN4fdulK5tVf-g9Vh4',
    appId: '1:171530435946:ios:88b7c4f688cc7d2c957913',
    messagingSenderId: '171530435946',
    projectId: 'quest-baldy-dash',
    storageBucket: 'quest-baldy-dash.appspot.com',
    iosClientId: '171530435946-ip9fu7l0cqk4o13cha9pp26ouad0t0it.apps.googleusercontent.com',
    iosBundleId: 'com.example.baldyDashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD02YSEsR3HLwm8pbN4fdulK5tVf-g9Vh4',
    appId: '1:171530435946:ios:88b7c4f688cc7d2c957913',
    messagingSenderId: '171530435946',
    projectId: 'quest-baldy-dash',
    storageBucket: 'quest-baldy-dash.appspot.com',
    iosClientId: '171530435946-ip9fu7l0cqk4o13cha9pp26ouad0t0it.apps.googleusercontent.com',
    iosBundleId: 'com.example.baldyDashApp',
  );
}
